name: Déclenchement de la synchronisation
on: 
  push:
    branches:
      - main
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sur le code
      uses: actions/checkout@v2
    - name: Déclenchement de la synchonisation au niveau du repo connecté à netlify
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token $PAT" \
        https://api.github.com/repos/zlorgoncho1/app-snpay/actions/workflows/sync.yml/dispatches \
        -d "{\"ref\":\"main\"}"
